name: tickr
description: "A task Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.5.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  
  # State Management
  provider: ^6.1.2
  
  # Dependency Injection
  get_it: ^7.7.0
  
  # Local Storage
  shared_preferences: ^2.3.2
  
  # Date Formatting
  intl: ^0.19.0
  
  # Google Fonts
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  
  # Testing dependencies
  test: ^1.24.9
  mockito: ^5.4.4
  build_runner: ^2.4.9


flutter:


  uses-material-design: true

  assets:
    - assets/logo.png

